export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_STATION_BEGIN = 'CREATE_STATION_BEGIN';
export const CREATE_STATION_SUCCESS = 'CREATE_STATION_SUCCESS';
export const CREATE_STATION_ERROR = 'CREATE_STATION_ERROR';

export const GET_STATION_BEGIN = 'GET_STATIONS_BEGIN';
export const GET_STATION_SUCCESS = 'GET_STATIONS_SUCCESS';

export const SET_EDIT_STATION = 'SET_EDIT_STATION';

export const DELETE_STATION_BEGIN = 'DELETE_STATION_BEGIN';
export const DELETE_STATION_ERROR = 'DELETE_STATION_ERROR';

export const EDIT_STATION_BEGIN = 'EDIT_STATION_BEGIN';
export const EDIT_STATION_SUCCESS = 'EDIT_STATION_SUCCESS';
export const EDIT_STATION_ERROR = 'EDIT_STATION_ERROR';

export const SHOW_STATION_BEGIN = 'SHOW_STATION_BEGIN';
export const SHOW_STATION_SUCCESS = 'SHOW_STATION_SUCCESS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';