enum ActionType {
  DISPLAY_ALERT = "DISPLAY_ALERT",
  CLEAR_ALERT = "CLEAR_ALERT",

  HANDLE_CHANGE = "HANDLE_CHANGE",
  CLEAR_VALUES = "CLEAR_VALUES",

  CREATE_STATION_BEGIN = "CREATE_STATION_BEGIN",
  CREATE_STATION_SUCCESS = "CREATE_STATION_SUCCESS",
  CREATE_STATION_ERROR = "CREATE_STATION_ERROR",

  GET_STATION_BEGIN = "GET_STATION_BEGIN",
  GET_STATION_SUCCESS = "GET_STATION_SUCCESS",

  SET_EDIT_STATION = "SET_EDIT_STATION",

  DELETE_STATION_BEGIN = "DELETE_STATION_BEGIN",
  DELETE_STATION_ERROR = "DELETE_STATION_ERROR",

  EDIT_STATION_BEGIN = "EDIT_STATION_BEGIN",
  EDIT_STATION_SUCCESS = "EDIT_STATION_SUCCESS",
  EDIT_STATION_ERROR = "EDIT_STATION_ERROR",

  SHOW_STATION_BEGIN = "SHOW_STATION_BEGIN",
  SHOW_STATION_SUCCESS = "SHOW_STATION_SUCCESS",

  GET_JORNEY_BEGIN="GET_JORNEY_BEGIN",
  GET_JORNEY_SUCCESS = "GET_JORNEY_SUCCESS",

  CREATE_JORNEY_BEGINE="CREATE_JORNEY_BEGINE",
  CREATE_JORNEY_SUCCESS="CREATE_JORNEY_SUCCESS",
  
  CLEAR_FILTERS = "CLEAR_FILTERS",
  CHANGE_PAGE = "CHANGE_PAGE",

  HANDLE_SORT = "HANDLE_SORT",
  HANDLE_JORNEY_CALCULATION = "HANDLE_JORNEY_CALCULATION",

  GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN",
  GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS",

  TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR',
  TOGGLE_MODAL = 'TOGGLE_MODAL',
  CLOSE_MODAL="CLOSE_MODAL",
  LOAD_SCRIPT = "LOAD_SCRIPT",
  CLOSE_SCRIPT = "CLOSE_SCRIPT"
}

export default ActionType